hour_1 = abs(int(input()))
minute_1 = abs(int(input()))
second_1 = abs(int(input()))
time_1 = (hour_1 * 3600) + (minute_1 * 60) + (second_1)
hour_2 = abs(int(input()))
minute_2 = abs(int(input()))
second_2 = abs(int(input()))
time_2 = (hour_2 * 3600) + (minute_2 * 60) + (second_2)
print(time_2 - time_1)
